'use strict';
const $=id=>document.getElementById(id);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ball=n=>`<span class="ball b${Math.ceil(n/10)}">${n}</span>`;
const balls=arr=>`<div class="balls">${arr.map(ball).join('')}</div>`;
const when=s=>new Date(s).toLocaleString('ko-KR',{timeZone:'Asia/Seoul',dateStyle:'medium',timeStyle:'short'});
function gamesHTML(r){return r.games.map((g,i)=>{const m=r.result?.matches?.[i];const wins=r.result?.numbers||[];const bonus=r.result?.bonus;const display=g.map(n=>{const cls=wins.includes(n)?'matched-ball':n===bonus?'bonus-ball':'unmatched-ball';return r.result?`<span class="ball b${Math.ceil(n/10)} ${cls}" title="${wins.includes(n)?'당첨번호 일치':n===bonus?'보너스 번호':'불일치'}">${n}</span>`:ball(n)}).join('');const bonusHit=r.result&&g.includes(bonus);const label=m?(m.rank?`${m.rank}등 · ${m.hits}개 일치`:`${m.hits}개 일치${bonusHit?' + 보너스':''}`):'결과 대기';return `<div class="game"><span class="game-label">GAME ${String(i+1).padStart(2,'0')}</span><div class="balls">${display}</div><span class="game-right ${m?'hit':'waiting'}">${label}</span></div>`}).join('')}
function resultHTML(r){if(!r.result)return `<div class="muted">추첨 결과 발표 후 자동 대조됩니다. 자동 조회에 실패하면 결과 대기 상태를 유지합니다.</div>`;return `<div class="winning"><b>공식 당첨번호</b><div style="display:flex;gap:12px;align-items:center;flex-wrap:wrap">${balls(r.result.numbers)}<span class="muted">보너스</span>${ball(r.result.bonus)}</div><div class="muted" style="margin-top:12px">초록색 이중 테두리와 ✓: 당첨번호 일치 · 금색 테두리와 B: 보너스 · 회색: 불일치<br>결과 반영 ${esc(when(r.result.verified_at))} · <a href="${esc(r.result.source.startsWith('https://www.dhlottery.co.kr/')?r.result.source:'https://www.dhlottery.co.kr/')}" target="_blank" rel="noopener" style="text-decoration:underline">공식 결과 확인</a></div></div>`}
function stats(rounds){const done=rounds.filter(r=>r.result),matches=done.flatMap(r=>r.result.matches),best=Math.max(0,...matches.map(m=>m.hits));const hit3=matches.filter(m=>m.hits>=3).length;const items=[['게시 회차',rounds.length+'회'],['대조 완료',done.length+'회'],['최고 일치',best+'개'],['3개 이상 일치',hit3+'게임']];$('stat-grid').innerHTML=items.map(([l,v])=>`<div class="stat"><b>${v}</b><span>${l}</span></div>`).join('')}
async function main(){try{const res=await fetch('./data/rounds.json?t='+Date.now(),{cache:'no-store'});if(!res.ok)throw Error('데이터 요청 실패');const data=await res.json();const rounds=(data.rounds||[]).slice().sort((a,b)=>Number(b.round)-Number(a.round));if(!rounds.length){$('current').innerHTML='<div class="skeleton">아직 게시된 번호가 없습니다.</div>';stats([]);return}const r=rounds[0];$('week-status').textContent=r.result?'추첨 완료':'결과 대기';$('current').innerHTML=`<article class="card"><div class="round-head"><div><h3>${r.round}회</h3><div class="muted">추첨일 ${esc(r.draw_date)} · 게시 ${esc(when(r.published_at))}</div></div><span class="pill">5 GAMES</span></div>${gamesHTML(r)}${resultHTML(r)}</article>`;stats(rounds);$('history-list').innerHTML=rounds.slice(1).map(x=>`<details class="archive"><summary><strong>${x.round}회 · ${esc(x.draw_date)}</strong><span class="muted">${x.result?'대조 완료':'결과 대기'}　⌄</span></summary><div class="archive-body"><p class="muted">최초 게시 ${esc(when(x.published_at))}</p>${gamesHTML(x)}${resultHTML(x)}</div></details>`).join('')||'<div class="skeleton">다음 주부터 지난 기록이 이곳에 누적됩니다.</div>'}catch(err){$('current').innerHTML=`<div class="skeleton">데이터를 불러오지 못했습니다. 잠시 후 다시 시도해 주세요.<br><small>${esc(err.message)}</small></div>`;}}
main();
